/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.sql.*;
import static javaapplication2.Login.uid;
/**
 *
 * @author ROHIT
 */


public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    Connection con;
Statement st;
 String str;
ResultSet rs;
int tt=1800;
int qna=0;
int ri;
Timer time=new Timer(1000, new ActionListener() {
       
        public void actionPerformed(ActionEvent e) {
           tt--;
           if(tt>=0)
           {
               int m=0,sec=0;
               m=tt/60;
               sec=tt-(m*60);
              if(sec>9)
               tim.setText("0"+m+":"+sec);
              else
                  tim.setText("0"+m+":0"+sec);
           }
           else
           {
               dispose();
           }
               
        }
    });
{
    
}

    public home() {
        initComponents();
        serverconnection();
        firstrecord();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        j15 = new javax.swing.JButton();
        j16 = new javax.swing.JButton();
        j20 = new javax.swing.JButton();
        j17 = new javax.swing.JButton();
        j18 = new javax.swing.JButton();
        j19 = new javax.swing.JButton();
        j21 = new javax.swing.JButton();
        j26 = new javax.swing.JButton();
        j28 = new javax.swing.JButton();
        j22 = new javax.swing.JButton();
        j24 = new javax.swing.JButton();
        j25 = new javax.swing.JButton();
        j23 = new javax.swing.JButton();
        j27 = new javax.swing.JButton();
        j30 = new javax.swing.JButton();
        j31 = new javax.swing.JButton();
        j29 = new javax.swing.JButton();
        j32 = new javax.swing.JButton();
        j34 = new javax.swing.JButton();
        j35 = new javax.swing.JButton();
        j33 = new javax.swing.JButton();
        j37 = new javax.swing.JButton();
        j38 = new javax.swing.JButton();
        j36 = new javax.swing.JButton();
        j39 = new javax.swing.JButton();
        j40 = new javax.swing.JButton();
        j8 = new javax.swing.JButton();
        j9 = new javax.swing.JButton();
        j13 = new javax.swing.JButton();
        j10 = new javax.swing.JButton();
        j11 = new javax.swing.JButton();
        j12 = new javax.swing.JButton();
        j14 = new javax.swing.JButton();
        j6 = new javax.swing.JButton();
        j3 = new javax.swing.JButton();
        j2 = new javax.swing.JButton();
        j1 = new javax.swing.JButton();
        j4 = new javax.swing.JButton();
        j7 = new javax.swing.JButton();
        j5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtf1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jl1 = new javax.swing.JLabel();
        tim = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jrb1 = new javax.swing.JRadioButton();
        jrb2 = new javax.swing.JRadioButton();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        j15.setText("15");
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });

        j16.setText("16");
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });

        j20.setText("20");
        j20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j20ActionPerformed(evt);
            }
        });

        j17.setText("17");
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });

        j18.setText("18");
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });

        j19.setText("19");
        j19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j19ActionPerformed(evt);
            }
        });

        j21.setText("21");
        j21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j21ActionPerformed(evt);
            }
        });

        j26.setText("26");
        j26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j26ActionPerformed(evt);
            }
        });

        j28.setText("28");
        j28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j28ActionPerformed(evt);
            }
        });

        j22.setText("22");
        j22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j22ActionPerformed(evt);
            }
        });

        j24.setText("24");
        j24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j24ActionPerformed(evt);
            }
        });

        j25.setText("25");
        j25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j25ActionPerformed(evt);
            }
        });

        j23.setText("23");
        j23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j23ActionPerformed(evt);
            }
        });

        j27.setText("27");
        j27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j27ActionPerformed(evt);
            }
        });

        j30.setText("30");
        j30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j30ActionPerformed(evt);
            }
        });

        j31.setText("31");
        j31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j31ActionPerformed(evt);
            }
        });

        j29.setText("29");
        j29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j29ActionPerformed(evt);
            }
        });

        j32.setText("32");
        j32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j32ActionPerformed(evt);
            }
        });

        j34.setText("34");
        j34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j34ActionPerformed(evt);
            }
        });

        j35.setText("35");
        j35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j35ActionPerformed(evt);
            }
        });

        j33.setText("33");
        j33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j33ActionPerformed(evt);
            }
        });

        j37.setText("37");
        j37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j37ActionPerformed(evt);
            }
        });

        j38.setText("38");
        j38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j38ActionPerformed(evt);
            }
        });

        j36.setText("36");
        j36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j36ActionPerformed(evt);
            }
        });

        j39.setText("39");
        j39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j39ActionPerformed(evt);
            }
        });

        j40.setText("40");
        j40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j40ActionPerformed(evt);
            }
        });

        j8.setText("08");
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j9.setText("09");
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        j13.setText("13");
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });

        j10.setText("10");
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });

        j11.setText("11");
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });

        j12.setText("12");
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });

        j14.setText("14");
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });

        j6.setText("06");
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j3.setText("03");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        j2.setText("02");
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j1.setText("01");
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j4.setText("04");
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j7.setText("07");
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        j5.setText("05");
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(j29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtf1.setEditable(false);
        jtf1.setColumns(20);
        jtf1.setLineWrap(true);
        jtf1.setRows(5);
        jtf1.setWrapStyleWord(true);
        jtf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtf1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jtf1);

        jLabel1.setText("Question No.");

        jLabel2.setText("User I'd");

        jl2.setText("jLabel3");

        jl1.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(tim, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jl2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jl1)
                        .addComponent(tim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jl2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jrb1);
        jrb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb1ActionPerformed(evt);
            }
        });

        bg.add(jrb2);
        jrb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb2ActionPerformed(evt);
            }
        });

        bg.add(jrb3);

        bg.add(jrb4);
        jrb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 102));
        jButton3.setText("Next");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jrb4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrb3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrb2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrb1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(147, 147, 147))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb1)
                .addGap(18, 18, 18)
                .addComponent(jrb2)
                .addGap(18, 18, 18)
                .addComponent(jrb3)
                .addGap(18, 18, 18)
                .addComponent(jrb4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Result rel=new Result();
                rel.show();
                dispose();
               saveserver();
//      answe();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
        try
        {
            rs.next();
            jtf1.setText(rs.getString("question"));
            jl1.setText(rs.getString("No"));
            jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e)
                {
                    
                }
          bg.clearSelection();
      
     
      
       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jrb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb4ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_jrb4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            rs.previous();
            jtf1.setText(rs.getString("question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(3);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
       
    }//GEN-LAST:event_j3ActionPerformed

    private void jrb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowStateChanged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseClicked

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
        // TODO add your handling code here:
        try{
        rs.first();
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e)
        {
            
        }
        
      
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(2);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_j2ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(4);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(5);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(6);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j6ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
        // TODO add your handling code here:
        
        try{
        rs.absolute(7);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
        
    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(8);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(9);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j9ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(10);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j10ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(11);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j11ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(12);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j12ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(13);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j13ActionPerformed

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(14);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j14ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(15);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j15ActionPerformed

    private void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(16);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j16ActionPerformed

    private void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(17);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j17ActionPerformed

    private void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(18);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j18ActionPerformed

    private void j19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j19ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(19);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j19ActionPerformed

    private void j20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j20ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(20);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j20ActionPerformed

    private void j21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j21ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(21);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j21ActionPerformed

    private void j22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j22ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(22);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j22ActionPerformed

    private void j23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j23ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(23);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j23ActionPerformed

    private void j24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j24ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(24);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j24ActionPerformed

    private void j25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j25ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(25);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j25ActionPerformed

    private void j26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j26ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(26);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j26ActionPerformed

    private void j27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j27ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(27);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j27ActionPerformed

    private void j28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j28ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(28);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j28ActionPerformed

    private void j29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j29ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(29);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j29ActionPerformed

    private void j30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j30ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(30);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j30ActionPerformed

    private void j31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j31ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(31);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j31ActionPerformed

    private void j32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j32ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(32);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j32ActionPerformed

    private void j33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j33ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(33);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j33ActionPerformed

    private void j34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j34ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(34);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j34ActionPerformed

    private void j35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j35ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(35);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j35ActionPerformed

    private void j36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j36ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(36);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j36ActionPerformed

    private void j37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j37ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(37);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j37ActionPerformed

    private void j38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j38ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(38);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j38ActionPerformed

    private void j39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j39ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(39);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j39ActionPerformed

    private void j40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j40ActionPerformed
        // TODO add your handling code here:
        try{
        rs.absolute(40);
        jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("No"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_j40ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        time.start();
    }//GEN-LAST:event_formWindowOpened

    private void jtf1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf1FocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtf1FocusLost

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        try{
            
            ri=Integer.parseInt(rs.getString("correctanswer"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         saveserver();
    }//GEN-LAST:event_jButton3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    public final void firstrecord()
{
    try
        {
            rs.first();
            jtf1.setText(rs.getString("Question"));
            jl1.setText(rs.getString("no"));
             jl2.setText(uid);
            jrb1.setText(rs.getString("answer1"));
            jrb2.setText(rs.getString("answer2"));
            jrb3.setText(rs.getString("answer3"));
            jrb4.setText(rs.getString("answer4"));
         
        }
        catch(Exception e)
                {
                    
                }

     
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton j1;
    private javax.swing.JButton j10;
    private javax.swing.JButton j11;
    private javax.swing.JButton j12;
    private javax.swing.JButton j13;
    private javax.swing.JButton j14;
    private javax.swing.JButton j15;
    private javax.swing.JButton j16;
    private javax.swing.JButton j17;
    private javax.swing.JButton j18;
    private javax.swing.JButton j19;
    private javax.swing.JButton j2;
    private javax.swing.JButton j20;
    private javax.swing.JButton j21;
    private javax.swing.JButton j22;
    private javax.swing.JButton j23;
    private javax.swing.JButton j24;
    private javax.swing.JButton j25;
    private javax.swing.JButton j26;
    private javax.swing.JButton j27;
    private javax.swing.JButton j28;
    private javax.swing.JButton j29;
    private javax.swing.JButton j3;
    private javax.swing.JButton j30;
    private javax.swing.JButton j31;
    private javax.swing.JButton j32;
    private javax.swing.JButton j33;
    private javax.swing.JButton j34;
    private javax.swing.JButton j35;
    private javax.swing.JButton j36;
    private javax.swing.JButton j37;
    private javax.swing.JButton j38;
    private javax.swing.JButton j39;
    private javax.swing.JButton j4;
    private javax.swing.JButton j40;
    private javax.swing.JButton j5;
    private javax.swing.JButton j6;
    private javax.swing.JButton j7;
    private javax.swing.JButton j8;
    private javax.swing.JButton j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JRadioButton jrb1;
    private javax.swing.JRadioButton jrb2;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JTextArea jtf1;
    private javax.swing.JLabel tim;
    // End of variables declaration//GEN-END:variables

    private void serverconnection() 
    {
        try{
        Class.forName("com.mysql.jdbc.Driver");
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
                
                 st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                 str="select * from addquestions";
                 rs=st.executeQuery(str);
                               
        }    
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    private void answe()
    {
        
       
        
        try
        {
             int nn=0;
            Class.forName("com.mysql.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
             st=con.createStatement();
             str="select * from useranswer";
             ResultSet rsc=st.executeQuery(str);
//             rs=st.executeQuery(str);
             {    
               nn=Integer.parseInt(rs.getString("No"));
          
                switch(nn){
                    case 1:
                        j1.setBackground(Color.BLUE);
                        break;
                    case 2:
                        j2.setBackground(Color.BLUE);
                        break;
                    case 3:
                        j3.setBackground(Color.BLUE);
                        break;
                    case 4:
                        j4.setBackground(Color.BLUE);
                        break;
                       case 5:
                        j5.setBackground(Color.BLUE);
                        break;
                        case 6:
                        j6.setBackground(Color.BLUE);
                        break;
                        case 7:
                        j7.setBackground(Color.BLUE);
                        break;
                        case 8:
                        j8.setBackground(Color.BLUE);
                        break;
                        case 9:
                        j9.setBackground(Color.BLUE);
                        break;
                        case 10:
                        j10.setBackground(Color.BLUE);
                        break;
                    case 11:
                        j11.setBackground(Color.BLUE);
                        break;
                    case 12:
                        j12.setBackground(Color.BLUE);
                        break;
                    case 13:
                        j13.setBackground(Color.BLUE);
                        break;
                    case 14:
                        j14.setBackground(Color.BLUE);
                        break;
                    case 15:
                        j15.setBackground(Color.BLUE);
                        break;
                        case 16:
                        j6.setBackground(Color.BLUE);
                        break;
                        case 17:
                        j17.setBackground(Color.BLUE);
                        break;
                        case 18:
                        j18.setBackground(Color.BLUE);
                        break;
                        case 19:
                        j19.setBackground(Color.BLUE);
                        break;
                        case 20:
                        j20.setBackground(Color.BLUE);
                        break;
                case 21:
                        j21.setBackground(Color.BLUE);
                        break;
                    case 22:
                        j2.setBackground(Color.BLUE);
                        break;
                    case 23:
                        j23.setBackground(Color.BLUE);
                        break;
                        case 24:
                        j24.setBackground(Color.BLUE);
                        break;
                       case 25:
                        j25.setBackground(Color.BLUE);
                        break;
                        case 26:
                        j26.setBackground(Color.BLUE);
                        break;
                        case 27:
                        j27.setBackground(Color.BLUE);
                        break;
                        case 28:
                        j28.setBackground(Color.BLUE);
                        break;
                        case 29:
                        j29.setBackground(Color.BLUE);
                        break;
                        case 30:
                        j30.setBackground(Color.BLUE);
                        break;
                    case 31:
                        j1.setBackground(Color.BLUE);
                        break;
                    case 32:
                        j32.setBackground(Color.BLUE);
                        break;
                    case 33:
                        j33.setBackground(Color.BLUE);
                        break;
                    case 34:
                        j34.setBackground(Color.BLUE);
                        break;
                       case 35:
                        j35.setBackground(Color.BLUE);
                        break;
                        case 36:
                        j36.setBackground(Color.BLUE);
                        break;
                        case 37:
                        j37.setBackground(Color.BLUE);
                        break;
                        case 38:
                        j38.setBackground(Color.BLUE);
                        break;
                        case 39:
                        j39.setBackground(Color.BLUE);
                        break;
                        case 40:
                        j40.setBackground(Color.BLUE);
                        break;}
                    
             }
                
       st.close();
                con.close();
                
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(null,e); 
        }
        

       
    }
    private void saveserver()
    {
        int usan=0;
        int c=0;
       if(jrb1.isSelected())
        {
           usan=1;
           answe();
          c=1;
           
        }
       if(jrb2.isSelected())
        {
             answe();
            usan=2;
            c=1;
        }
       if(jrb3.isSelected())
        {
             answe();
            usan=3;
          c=1;
        }
       if(jrb4.isSelected())
        {
             answe();
            usan=4;
            c=1;
        }

       try{
         try 
        {
            
            c=0;
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
          
             
            
                 st=con.createStatement();
                st.executeUpdate("insert into useranswer values('"+uid+"','"+jl1.getText()+"','"+usan+"','"+ri+"')");
               
               
                st.close();
                con.close();
               throw new SQLIntegrityConstraintViolationException ("Duplicate entry");  
                 
        }
        catch(SQLIntegrityConstraintViolationException e)
        {
           
        }
         Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/user_ac","root","");
       
      String sql="select * from useranswer where No=?";
       PreparedStatement prstm=con.prepareStatement(sql);
       prstm.setString(1,jl1.getText());
       
     
       
       ResultSet rst=prstm.executeQuery();
      
       if(rst.next())
       {
           
           
          
                prstm.executeUpdate("update useranswer set ans='"+usan+"' where No='"+jl1.getText()+"'");
            

       }
       
       con.close();
      prstm.close();
       
       }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null, e);
         }

        }

         
    }

